# Generated by Django 4.1.4 on 2023-01-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedColleges',
            fields=[
                ('college', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scraped_colleges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapedTowns',
            fields=[
                ('town', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area_in_sq_mi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_area', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevation_in_ft', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraped_towns',
                'managed': False,
            },
        ),
    ]
